Add support for `target` and `apply` scripts, update README.md

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -70,12 +70,17 @@ function find_installable() {
     find "$@" \
         \( \( -type d -execdir test -e '{}.symlink' \; -prune \) -o -type f -o -type l \) ! -name '*.symlink' -print |
         # 1. Discard all but the first instance of each file
-        # 2. In column 1, print '1' if the file is a `configure` script, '0' otherwise
+        # 2. In column 1, print:
+        #    - '-2' if the file is a `target` script
+        #    - '-1' if the file is a `configure` script
+        #    -  '1' if the file is an `apply` script
+        #    -  '0' otherwise
         # 3. In column 2, print the path name of the file relative to `app_dir/files`
         # 4. In column 3, print the absolute path name of the file
         awk -v df_root_len=${#df_root} -v app_len=${#app} -f "$df_root/bin/lib/filter-installable.awk" |
-        # Move `configure` to the top of the list and sort remaining entries by relative path
-        LC_ALL=C sort -t $'\t' -k1,1nr -k2,2
+        # Move `target` and `configure` scripts to the top of the list, `apply` to the end, and sort remaining
+        # entries by relative path
+        LC_ALL=C sort -t $'\t' -k1,1n -k2,2
 }
 
 df_root=$(realpath "${BASH_SOURCE[0]}") &&
@@ -130,12 +135,19 @@ for app in ${apps+"${apps[@]}"}; do
     # Get a list of directories that actually exist by expanding !(?)
     app_dirs=($(eval printf '%s\\n' $(printf '%q!(?)\n' "${app_roots[@]/%//$app}")))
     # Mitigate race condition where settings for an app are removed before they can be applied
-    [[ -n ${app_dirs+1} ]] || die "app disappeared: $app"
-    while IFS=$'\t' read -r configure rel_path path; do
-        if ((configure)); then
-            [[ -f $path ]] && [[ -x $path ]] || die "configure script not executable: $path"
-            echo " -> Running configure script: $path"
-            "$path" "${app_dirs[@]}" && status=0 || status=$?
+    [[ -n ${app_dirs+1} ]] || continue
+    export df_target=~
+    while IFS=$'\t' read -r run rel_path path; do
+        if ((run)); then
+            [[ -f $path ]] && [[ -x $path ]] || die "not executable: $path"
+            echo " -> Running: $path"
+            if [[ $rel_path == target ]]; then
+                target=$("$path" "${app_dirs[@]}") &&
+                    { [[ -n $target ]] || die "invalid target"; } &&
+                    df_target=$target
+            else
+                "$path" "${app_dirs[@]}"
+            fi && status=0 || status=$?
             case "$status" in
             0)
                 # Continue to the next step
@@ -146,7 +158,7 @@ for app in ${apps+"${apps[@]}"}; do
                 continue 2
                 ;;
             2)
-                # Record the error and skip to the next application
+                # Record a non-critical error and skip to the next application
                 error_apps[${#error_apps[@]}]=$app
                 continue 2
                 ;;
@@ -155,7 +167,7 @@ for app in ${apps+"${apps[@]}"}; do
                 ;;
             esac
         fi
-        target=~/$rel_path
+        target=$df_target/$rel_path
         link_file "$path" "$target"
     done < <(find_installable "$app" "${app_dirs[@]}")
 done
